version: "3.8"

services:

  webservice:
    build: 
      context: ./app
      dockerfile: Dockerfile
    cpus: 8.0 # Change this to the number of cores to boost performance
    mem_limit: 6144m
    ports:
      - 5000:5000
    container_name: webservice
    environment:
      - PORT=5000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_SERVER=mongodb
      - MONGO_INITDB_DATABASE=sampledb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always
    volumes:
      - ./app:/var/www
    links:
      - mongodb
    networks:
      - mongo_net

  webserver:
    container_name: webserver
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webservice
    networks:
      - mongo_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped 
    ports:
      - 27017:27017 
    environment:
      - MONGO_INITDB_DATABASE=sampledb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - ./mongo-entrypoint/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net

volumes:
  nginxdata:
    driver: local
  mongodb:
    driver: local
  mongoconfig:
    driver: local

networks:
  mongo_net:
    driver: bridge
