version: "3.8"

services:

  webservice:
    build: 
      context: ./app
      dockerfile: Dockerfile
    cpus: 8.0 # Change this to the number of cores to boost performance
    mem_limit: 6144m
    ports:
      - 5000:5000
    container_name: webservice
    environment:
      - PORT=5000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_SERVER=mongodb
      - MONGO_INITDB_DATABASE=sampledb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always
    volumes:
      - ./app:/var/www
    links:
      - mongodb
    networks:
      - backend_net
      - frontend_net

  webserver:
    container_name: webserver
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webservice
    networks:
      - frontend_net

  dnsduck:
    container_name: dnsduck
    image: lscr.io/linuxserver/duckdns:latest
    restart: unless-stopped
    dns:
      - 1.1.1.1
    volumes:
      - dnsduck_config:/data/dnsduck
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC 
      - SUBDOMAINS=lockedsite.duckdns.org
      - TOKEN=29986796-52d6-49d6-b310-677f90d0e80d
      - LOG_FILE=true
    networks:
      - frontend_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped 
    ports:
      - 27017:27017 
    environment:
      - MONGO_INITDB_DATABASE=sampledb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - ./mongo-entrypoint/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - backend_net

volumes:
  nginxdata:
    driver: local
  mongodb:
    driver: local
  mongoconfig:
    driver: local
  dnsduck_config:
    driver: local

networks:
  backend_net:
    name: backend_net
    driver: bridge
  frontend_net:
    name: frontend_net
    driver: bridge
    external: true
